# Generated by Django 5.1.4 on 2025-02-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("member_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("mob", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                ("doj", models.DateField()),
                ("doj_service", models.DateField()),
                ("maximum_period", models.IntegerField()),
                (
                    "max_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("city", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Teaching", "Teaching Staff"),
                            ("Non-Teaching", "Non-Teaching Staff"),
                        ],
                        default="Non-Teaching",
                        max_length=20,
                    ),
                ),
                ("has_loan", models.BooleanField(default=False)),
                (
                    "max_eligibity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=18),
                ),
            ],
        ),
    ]
