# Generated by Django 5.1.4 on 2025-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneyapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="max_eligibity",
            field=models.DecimalField(decimal_places=2, default="NUll", max_digits=18),
        ),
    ]
