# Generated by Django 4.2.11 on 2025-02-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Teaching', 'Teaching Staff'), ('Non-Teaching', 'Non-Teaching Staff')], default='Non-Teaching', max_length=20),
        ),
    ]
