# Generated by Django 5.1.4 on 2025-02-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneyapp", "0002_alter_member_max_eligibity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="max_eligibity",
            field=models.DecimalField(decimal_places=2, default="NULL", max_digits=18),
        ),
        migrations.AlterField(
            model_name="member",
            name="mob",
            field=models.IntegerField(max_length=15),
        ),
    ]
