# Generated by Django 5.1.4 on 2025-02-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneyapp", "0004_alter_member_max_eligibity_alter_member_mob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="max_eligibity",
            field=models.FloatField(default="NULL"),
        ),
    ]
