# Generated by Django 5.1.5 on 2025-04-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0005_alter_member_max_eligibity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='max_eligibity',
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=50, unique=True)),
                ('disp_date', models.DateField()),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repayment_start_date', models.DateField()),
                ('repayment_period', models.IntegerField()),
                ('monthly_repayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='moneyapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('principal_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repayment_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneyapp.member')),
            ],
        ),
    ]
