# Generated by Django 5.1.4 on 2025-05-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneyapp", "0007_repayment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loanrepayment",
            options={"ordering": ("member", "repayment_number")},
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="outstanding_balance",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="repayment_number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Repayment",
        ),
    ]
