# Generated by Django 5.2.4 on 2026-02-10 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0008_alter_loanrepayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='rd_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='mob',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')]),
        ),
        migrations.AddConstraint(
            model_name='loanrepayment',
            constraint=models.UniqueConstraint(fields=('member', 'repayment_number'), name='unique_member_repayment'),
        ),
    ]
